<a href="https://colab.research.google.com/github/k-vinamr/data_embedding_anime_recommendation_system/blob/main/Cosine_similarity_anime_prediction_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
anime_data = pd.read_csv('anime_list.csv')

In [ ]:
anime_data.head()

Unnamed: 0                                Name Type  Score  Score Rank  \
0           0    Fullmetal Alchemist: Brotherhood   TV   9.14           1   
1           1                        Spy x Family   TV   9.09           2   
2           2  Shingeki no Kyojin Season 3 Part 2   TV   9.08           3   
3           3                         Steins;Gate   TV   9.08           4   
4           4                            Gintama°   TV   9.08           5   

   Popularity Rank                     Air Date  \
0                3   Apr 5, 2009 to Jul 4, 2010   
1              350             Apr 9, 2022 to ?   
2               32  Apr 29, 2019 to Jul 1, 2019   
3               13  Apr 6, 2011 to Sep 14, 2011   
4              335  Apr 8, 2015 to Mar 30, 2016   

                                      Studio  Num. of episodes  \
0                                  ['Bones']                64   
1  ['Wit Studio', '            CloverWorks']                12   
2                             ['Wit Studio']                10   
3                              ['White Fox']                24   
4                  ['Bandai Namco Pictures']                51   

                                        Genres  \
0  ['Action', 'Adventure', 'Drama', 'Fantasy']   
1                         ['Action', 'Comedy']   
2                          ['Action', 'Drama']   
3              ['Drama', 'Sci-Fi', 'Suspense']   
4               ['Action', 'Comedy', 'Sci-Fi']   

                                           Theme(s) Demographic  
0                                      ['Military']     Shounen  
1                                     ['Childcare']     Shounen  
2                  ['Gore', 'Military', 'Survival']     Shounen  
3                  ['Psychological', 'Time Travel']        None  
4  ['Gag Humor', 'Historical', 'Parody', 'Samurai']     Shounen

In [ ]:
anime_data=anime_data.rename(columns={'Unnamed: 0':'Index'})
print(anime_data)

      Index                                              Name     Type  Score  \
0         0                  Fullmetal Alchemist: Brotherhood       TV   9.14   
1         1                                      Spy x Family       TV   9.09   
2         2                Shingeki no Kyojin Season 3 Part 2       TV   9.08   
3         3                                       Steins;Gate       TV   9.08   
4         4                                          Gintama°       TV   9.08   
...     ...                                               ...      ...    ...   
1995   1995                                Shugo Chara!! Doki       TV   7.41   
1996   1996  Steins;Gate: Soumei Eichi no Cognitive Computing      ONA   7.41   
1997   1997                   Taiho Shichau zo: Second Season       TV   7.41   
1998   1998            Tanaka-kun wa Itsumo Kedaruge Specials  Special   7.41   
1999   1999              Tiger & Bunny Movie 1: The Beginning    Movie   7.41   

      Score Rank  Popularit

In [ ]:
anime_data.shape

(2000, 12)

In [ ]:
anime_data['Score'] = anime_data['Score'].astype(str)

In [ ]:
selected_features = ['Score','Genres','Demographic','Theme(s)']
print(selected_features)

['Score', 'Genres', 'Demographic', 'Theme(s)']


In [ ]:
for feature in selected_features:
    anime_data[feature] = anime_data[feature].fillna('')

In [ ]:
combined_feature = anime_data['Score']+' '+anime_data['Genres']+' '+anime_data['Demographic']+' '+anime_data['Theme(s)']


In [ ]:
print(combined_feature)

0       9.14 ['Action', 'Adventure', 'Drama', 'Fantasy...
1         9.09 ['Action', 'Comedy'] Shounen ['Childcare']
2       9.08 ['Action', 'Drama'] Shounen ['Gore', 'Mil...
3       9.08 ['Drama', 'Sci-Fi', 'Suspense'] None ['Ps...
4       9.08 ['Action', 'Comedy', 'Sci-Fi'] Shounen ['...
                              ...                        
1995    7.41 ['Comedy'] Shoujo ['Mahou Shoujo', 'School']
1996              7.41 ['Comedy', 'Sci-Fi'] None ['None']
1997    7.41 ['Action', 'Comedy'] Shounen ['Detective'...
1998    7.41 ['Comedy', 'Slice of Life'] None ['Iyashi...
1999    7.41 ['Action', 'Comedy', 'Mystery'] None ['Ad...
Length: 2000, dtype: object


In [ ]:
#converting text data to feature vectors
#creation of an instance
vectorizer= TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_feature)
print(feature_vectors)

  (0, 138)	0.40920869783963004
  (0, 164)	0.26141736705442
  (0, 111)	0.27981423619012935
  (0, 108)	0.25112100653373204
  (0, 92)	0.28814433134935596
  (0, 90)	0.228364925700642
  (0, 12)	0.6983364090025104
  (1, 100)	0.6078461656126801
  (1, 102)	0.21084195008002088
  (1, 8)	0.6855337520879978
  (1, 164)	0.2566247816775907
  (1, 90)	0.22417829335931871
  (2, 174)	0.516023374465725
  (2, 118)	0.4505849991126486
  (2, 7)	0.5391648022405205
  (2, 138)	0.3383684733896387
  (2, 164)	0.2161620607644289
  (2, 108)	0.20764815622318203
  (2, 90)	0.18883149770034313
  (3, 178)	0.42572202739159964
  (3, 177)	0.42572202739159964
  (3, 151)	0.32247538563427297
  (3, 142)	0.12576687374004972
  (3, 175)	0.37885380953513387
  (3, 113)	0.23194259763210684
  :	:
  (1996, 159)	0.3867381972535449
  (1996, 102)	0.26463154488848895
  (1997, 36)	0.5428148762878683
  (1997, 107)	0.4911889216650361
  (1997, 183)	0.5479616942089537
  (1997, 102)	0.21296956770591663
  (1997, 164)	0.25921439635593935
  (1997, 9

### **COSINE SIMILARITY**



In [ ]:
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)

[[1.         0.11828063 0.29023914 ... 0.11947421 0.         0.04540368]
 [0.11828063 1.         0.09780446 ... 0.1621868  0.04677797 0.08399724]
 [0.29023914 0.09780446 1.         ... 0.09879141 0.         0.03754361]
 ...
 [0.11947421 0.1621868  0.09879141 ... 1.         0.35420184 0.34355357]
 [0.         0.04677797 0.         ... 0.35420184 1.         0.33705001]
 [0.04540368 0.08399724 0.03754361 ... 0.34355357 0.33705001 1.        ]]
(2000, 2000)


### **USER INPUT FOR ANIME**

In [ ]:
anime_name = input('Enter your favorite Anime:')

Enter your favorite Anime:Gintama


In [ ]:
#creating a list with all anime names from the dataset
list_anime_titles = anime_data['Name'].tolist()
print(list_anime_titles)

['Fullmetal Alchemist: Brotherhood', 'Spy x Family', 'Shingeki no Kyojin Season 3 Part 2', 'Steins;Gate', 'Gintama°', "Gintama'", 'Gintama: The Final', 'Hunter x Hunter (2011)', 'Fruits Basket: The Final', "Gintama': Enchousen", 'Ginga Eiyuu Densetsu', 'Gintama.', 'Kaguya-sama wa Kokurasetai: Ultra Romantic', '3-gatsu no Lion 2nd Season', 'Koe no Katachi', 'Gintama', 'Violet Evergarden Movie', 'Clannad: After Story', 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', 'Code Geass: Hangyaku no Lelouch R2', 'Owarimonogatari 2nd Season', 'Shingeki no Kyojin: The Final Season Part 2', 'Kimetsu no Yaiba: Yuukaku-hen', 'Gintama.: Shirogane no Tamashii-hen - Kouhan-sen', 'Kimi no Na wa.', 'Shingeki no Kyojin: The Final Season', 'Monster', 'Mob Psycho 100 II', 'Gintama.: Shirogane no Tamashii-hen', 'Kizumonogatari III: Reiketsu-hen', 'Shiguang Dailiren', 'Sen to Chihiro no Kamikakushi', 'Haikyuu!!: Karasuno Koukou vs. Shiratorizawa Gakuen Koukou', 'Kingdom 3rd Season', 'Monogatari Series:

In [ ]:
# find the closest match for the anime provided by the user
find_cl_match = difflib.get_close_matches(anime_name,list_anime_titles)
print(find_cl_match)

['Gintama', 'Gintama°', 'Gintama.']


In [ ]:
close_match = find_cl_match[0]
print(close_match)

Gintama


In [ ]:
#finding the index of anime with the title
index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]
print(index_of_anime)

15


In [ ]:
#getting a list of similar anime
similarity_score = list(enumerate(similarity[index_of_anime]))
print(similarity_score)

[(0, 0.08676838208058105), (1, 0.11778848432256006), (2, 0.07174746074092793), (3, 0.10485541141466041), (4, 0.7768052176385466), (5, 0.7617780465770233), (6, 0.7500234361808844), (7, 0.0962651737532566), (8, 0.0), (9, 0.7768052176385466), (10, 0.11693461653859354), (11, 0.7669152021621374), (12, 0.02530954787719259), (13, 0.0), (14, 0.04160142137176147), (15, 1.0), (16, 0.31800298773387714), (17, 0.030946128873431126), (18, 0.6706530865231328), (19, 0.14828337547808956), (20, 0.040923994604082706), (21, 0.08519049710925514), (22, 0.20580948980012315), (23, 0.7768052176385466), (24, 0.0), (25, 0.07213175754156506), (26, 0.0), (27, 0.07107325265287742), (28, 0.7853932879537789), (29, 0.04605493102611444), (30, 0.0), (31, 0.0), (32, 0.03887462305007864), (33, 0.1516442516645047), (34, 0.031653857340467766), (35, 0.15946026102666136), (36, 0.0), (37, 0.0), (38, 0.07143529191324478), (39, 0.07431171614802987), (40, 0.038756442859491716), (41, 0.150118608343508), (42, 0.17583888679812804), 

In [ ]:
len(similarity_score)


2000

In [ ]:
#sorting anime based on their similarity score
sorted_similar_anime = sorted(similarity_score , key =lambda x:x[1], reverse= True)
print(sorted_similar_anime)

[(15, 1.0), (99, 0.8015714073410443), (142, 0.7979764178297742), (28, 0.7853932879537789), (4, 0.7768052176385466), (9, 0.7768052176385466), (23, 0.7768052176385466), (427, 0.7732452177758891), (11, 0.7669152021621374), (5, 0.7617780465770233), (6, 0.7500234361808844), (124, 0.729346116919641), (428, 0.7082839843946975), (18, 0.6706530865231328), (106, 0.6299198362543741), (162, 0.608126400968168), (1338, 0.608126400968168), (466, 0.5804325879630409), (1649, 0.5759429369189052), (1695, 0.5693974226673852), (246, 0.5686759530629875), (1906, 0.5321324076117206), (115, 0.5241174608936663), (911, 0.5202785849113096), (707, 0.5149128462728977), (1719, 0.5147881849293287), (1803, 0.5102153964906118), (822, 0.5097250410392469), (1731, 0.5081627307023955), (737, 0.5067219798262219), (742, 0.5067219798262219), (1696, 0.5033301278969936), (1344, 0.49899444720900443), (235, 0.4942601107615183), (1910, 0.49131629060382476), (1911, 0.49131629060382476), (1864, 0.490597224340709), (736, 0.4881156563

In [ ]:
# print the name of similar anime based on the Index
print('Anime Suggested for you :) \n')

i=1
for anime in sorted_similar_anime:
    Index=anime[0]
    title_from_index = anime_data[anime_data.Index==Index]['Name'].values[0]
    if(i<20):
        print(i,'.',title_from_index)
        i+=1

Anime Suggested for you :) 

1 . Gintama
2 . Gintama.: Porori-hen
3 . Gintama: Yorinuki Gintama-san on Theater 2D
4 . Gintama.: Shirogane no Tamashii-hen
5 . Gintama°
6 . Gintama': Enchousen
7 . Gintama.: Shirogane no Tamashii-hen - Kouhan-sen
8 . Gintama': Futon ni Haitte kara Buki Nokoshi ni Kizuite Neru ni Nerenai Toki mo Aru
9 . Gintama.
10 . Gintama'
11 . Gintama: The Final
12 . Gintama: The Semi-Final
13 . Gintama°: Umai-mono wa Atomawashi ni Suru to Yokodorisareru kara Yappari Saki ni Kue
14 . Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare
15 . Gintama Movie 1: Shinyaku Benizakura-hen
16 . Gintama°: Aizome Kaori-hen
17 . Osomatsu-san 2nd Season
18 . Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi
19 . Paniponi Dash!: Danjite Okonaeba Kishin mo Kore wo Saku


ANIME RECOMMENDATION SYSTEM


In [ ]:
anime_name = input('Enter your favorite Anime:')
list_anime_titles = anime_data['Name'].tolist()
find_cl_match = difflib.get_close_matches(anime_name,list_anime_titles)
close_match = find_cl_match[0]
index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]
similarity_score = list(enumerate(similarity[index_of_anime]))
sorted_similar_anime = sorted(similarity_score , key =lambda x:x[1], reverse= True)
print('Anime Suggested for you :) \n')

i=1
for anime in sorted_similar_anime:
    Index=anime[0]
    title_from_index = anime_data[anime_data.Index==Index]['Name'].values[0]
    demog_from_index = anime_data[anime_data.Index==Index]['Demographic'].values[0]
    if(i<20):
        print(i,'.',title_from_index, ([demog_from_index]))
        i+=1

Enter your favorite Anime:no game no life
Anime Suggested for you :) 

1 . No Game No Life ['None']
2 . Tsukimonogatari ['None']
3 . Black Clover ['Shounen']
4 . Quanzhi Gaoshou Zhi Dianfeng Rongyao ['None']
5 . Yu☆Gi☆Oh! Duel Monsters ['Shounen']
6 . D-Frag! ['Seinen']
7 . Yu☆Gi☆Oh! 5D's ['Shounen']
8 . Hikaru no Go: Hokuto Hai e no Michi ['Shounen']
9 . Shoubushi Densetsu Tetsuya ['Shounen']
10 . Hikaru no Go ['Shounen']
11 . Yu☆Gi☆Oh! The Dark Side of Dimensions ['Shounen']
12 . Zero no Tsukaima F ['None']
13 . Saki ['None']
14 . Saki Zenkoku-hen ['None']
15 . Pokemon Generations ['Kids']
16 . Saki Achiga-hen: Episode of Side-A Specials ['None']
17 . Shion no Ou ['None']
18 . Uchouten Kazoku 2 ['None']
19 . Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru ['None']


GUI CREATION

In [ ]:
import tkinter as tk
from tkinter import messagebox
import difflib
from PIL import ImageTk, Image


#create Tkinter GUI
root=tk.Tk()
root.title("Anime Recommendation System")
root.configure(bg="#222222")
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
root.rowconfigure(1,weight=1)






#define styling
title_font=("Arial",16,"bold")
root.option_add("*Font",title_font)

#define styling for labels
label_font=("Arial",12,"bold")
entry_font=("Arial",12)
button_font=("Arial",12,"bold")
button_bg="#3366CC"
button_fg="#FFFFFF"
button_active_bg="#25476D"
button_active_fg="#FFFFFF"

#create a canvas widget and set the bg image
try:
    bg_image=Image.open(r"D:\Users\User\Downloads\ani.gif")
    bg_image=bg_image.resize((1300,600),Image.ANTIALIAS)
    root.background=ImageTk.PhotoImage(bg_image)

    #create a canvas widget and place the bg on it
    canvas=tk.Canvas(root, width=900, height=400)
    canvas.grid(row=0,column=0,padx=10,pady=10,sticky="nsew")
    canvas.create_image(0,0,anchor=tk.NW,image=root.background)
except IOError:
    messagebox.showerror("Error","failed to load background image.")


#Create GUI elements - label for anime name input
name_label=tk.Label(root,text="Enter Anime Name:")
name_label.grid(row=0, column=0,padx=10,pady=10,sticky="w")




#create the entry field
entry = tk.Entry(root, font=entry_font)
entry.grid(row=0, column=1, padx=10, pady=10 , sticky="ew")



def get_recommendations():
    anime_name=entry.get()


#find closest match in the anime dataset
    list_anime_titles = anime_data['Name'].tolist()
    find_cl_match = difflib.get_close_matches(anime_name, list_anime_titles)
    if find_cl_match:
        close_match = find_cl_match[0]
        index_of_anime = anime_data[anime_data.Name == close_match]['Index'].values[0]

        # Compute similarity scores
        similarity_score = list(enumerate(similarity[index_of_anime]))
        sorted_similar_anime = sorted(similarity_score , key=lambda x: x[1], reverse=True)

        # Generate recommendations
        recommendations = []
        for i, anime in enumerate(sorted_similar_anime):
            if i < 20:
                Index = anime[0]
                title_from_index = anime_data[anime_data.Index == Index]['Name'].values[0]
                demog_from_index = anime_data[anime_data.Index == Index]['Demographic'].values[0]
                recommendations.append(f"{i+1}. {title_from_index} {demog_from_index}")

        messagebox.showinfo("Anime Recommendations For You :)","\n".join(recommendations))

    else:
        messagebox.showinfo("Anime Recommendations For You","No match found :(")

button = tk.Button(root, text="Get Recommendations",font=button_font, bg=button_bg, fg=button_fg,activebackground=button_active_bg, activeforeground=button_active_fg, command=get_recommendations)
button.grid(row=1, column=0 , padx=10 ,pady=10, sticky="ew")




#start the event loop
root.mainloop()

TclError: ignored